### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by solmersa** [ArkCase/arkcase-ce#329]
When using the password @rKc@3e and user arkcase-admin@arkcase.org, it displays in red "Authentication problem. Please contact your administrator", this happen in both Firefox and Chrome.
I'm using the version 3.3.1 at https://app.vagrantup.com/arkcase/boxes/arkcase-ce.  Did the credentials change?

**Comment by david-oc-miller** [comment]
@solmersa , in case you may still be interested in ArkCase after all this time, did you use the password @rKc@3e ?  If so, and you still get `Authentication problem`, can you send me the ArkCase log file?  In the vagrant VM, the log file should be /opt/app/arkcase/logs/catalina.out.

**Comment by solmersa** [comment]
Hi David, I used the password @rKc@3e (note the K capital) copied verbatim from the Instructions page (github turns to lowercase that in the message).

I will search for the logs and send them you.  

And yes I am still interested in Arkcase of course.

**Comment by david-oc-miller** [comment]
@solmersa ,

I have made some updates in this repository so you can try a newer version of ArkCase (v2021.02).

If you remove your existing VM via `vagrant destroy`, and `git pull` to pull these changes, you should be able to deploy ArkCase 2021.02 by using the instructions in the updated README. Be sure to `export ARKCASE_WEBAPP_VERSION=2021.02` before `vagrant up`. Also follow the other updated instructions in terms of setting the hostname correctly.

Sometime in the near future I'll push a pre-built 2021.02 Vagrant box to the Vagrant hub, but for now you would follow the instructions to build a box yourself using `packer`.

Thanks,
Dave

**Comment by david-oc-miller** [comment]
@solmersa , ArkCase 2021.03 should work now, following same instructions as above (only using 2021.03 instead of 2021.02).  Please let me know how it works.

**Comment by prdas31** [comment]
Hi, 
I'm using 2021.03.

I'm trying to build the CentOS box using packer and the installation is stuck after the VBox is created at the following line...

`PS D:\Workspaces\arkcase-setup\arkcase-ce-develop\arkcase-ce-develop\packer> D:\Workspaces\arkcase-setup\packer_1.8.4_windows_amd64\packer build centos7.json
virtualbox-iso: output will be in this color.

==> virtualbox-iso: Retrieving Guest additions
==> virtualbox-iso: Trying C:\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Trying file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso => C:/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Retrieving ISO
==> virtualbox-iso: Trying CentOS-7-x86_64-Minimal-2009.iso
==> virtualbox-iso: Trying CentOS-7-x86_64-Minimal-2009.iso?checksum=sha256%3A07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a
==> virtualbox-iso: CentOS-7-x86_64-Minimal-2009.iso?checksum=sha256%3A07b94e6b1a0b0260b94c83d6bb76b26bf7a310dc78d7a9c7432809fb9bc6194a => D:\Workspaces\arkcase-setup\arkcase-ce-develop\arkcase-ce-develop\packer\packer_cache\e476ea1d3ef3c2e3966a7081ac4239cd5ae5e8a3.iso
==> virtualbox-iso: Starting HTTP server on port 8819
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive output-virtualbox-iso\arkcase-centos-7-x86_64.vdi with size 131072 MiB...
==> virtualbox-iso: Mounting ISOs...
    virtualbox-iso: Mounting boot ISO...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 2296)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm arkcase-centos-7-x86_64 --memory 8192
    virtualbox-iso: Executing: modifyvm arkcase-centos-7-x86_64 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
    virtualbox-iso: The VM will be run headless, without a GUI. If you want to
    virtualbox-iso: view the screen of the VM, connect via VRDP without a password to
    virtualbox-iso: rdp://127.0.0.1:5936
==> virtualbox-iso: Waiting 10s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Using SSH communicator to connect: 127.0.0.1
==> virtualbox-iso: Waiting for SSH to become available...`

I tried to do a ssh/putty to the box using the username/password as given in the centos7.json file ("ssh_username": "root", "ssh_password": "@rKc@3e",) like this:

`ssh root@192.168.56.1
root@192.168.56.1's password:
Permission denied, please try again.
root@192.168.56.1's password:
Permission denied, please try again.
root@192.168.56.1's password:
root@192.168.56.1: Permission denied (publickey,password,keyboard-interactive).`

After trying for 2 hours or so, it fails and removes the VM.

Could you please help to resolve this?

Thanks
Pranabesh

**Comment by donavoncampbell** [comment]
Help... 

I'm using the Arkcase CE. 

username: arkcase-admin@arkcase.org
Password: @rkc@3e

Still not able to login

\help

**Comment by srinivasagunturu** [comment]
Hi @donavoncampbell ,

Have you followed the below instructions or any other instructions to install Arkcase-CE?

Install instruction from:
https://github.com/ArkCase/arkcase-ce
section: How to Create a New VM and Install ArkCase Yourself

**Comment by donavoncampbell** [comment]
I found the solution only in the Arkcase CE (AWS) page.... "A....Instance
ID..."

-dac

**Comment by srinivasagunturu** [comment]
Hi @donavoncampbell ,

Are you able to login to the Arkcase application?
If not, please try below.

userName: arkcase-admin@arkcase.org
password: @rKc@3e

userName: arkcase-admin@arkcase.org
password: AcMd3v$

**Comment by srinivasagunturu** [comment]
Hi @donavoncampbell 

If you are launching Arkcase on AWS, please follow the steps below.

1. Login to ArkCase.
2. Browse to your AWS ArkCase URL: https://dns_of_instance/arkcase
3. Click on the Username field on the login page and enter the admin username = [arkcase-admin@arkcase.org](mailto:arkcase-admin@arkcase.org)  
Enter password. The password for the admin user is formed of the uppercase A followed by the instance ID as shown on the AWS console. (For example, if the instance ID is "i-0d8a8a582b002572d", the password will be "Ai-0d8a8a582b002572d")
4.Click ‘Log In."

**Comment by donavoncampbell** [comment]
This worked for the AWS Arkcase CE

-dac

**Comment by srinivasagunturu** [comment]
Hi @donavoncampbell ,

Thanks for the confirmation. Do you require any additional information for this issue?

**Comment by donavoncampbell** [comment]
No...

Thanks.

I had a general question about Complaints, but not an issue... can you
guide me to where I can ask that question about feature?

-dac

**Comment by srinivasagunturu** [comment]
Hi @donavoncampbell ,

Should you have any questions or need additional assistance regarding Arkcase features, please reach out to us at [support@arkcase.com] (mailto:support@arkcase.com).
