### ISSUE TITLE
PROXY ERROR

### ISSUE THREAD

**Issue by Laddergrowth** [ArkCase/arkcase-ce#351]
I am using windows 10, to boot the VM, I add the 192.168.56.15 arkcase-ce.local (configured using the correct output by the VM), when going to
https://arkcase-ce.local/arkcase/

i am getting the following...
____________________________

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /arkcase/.

Reason: Error reading from remote server

__________________________

I tried adding new rules for the firewall but that dint work either.

What am i missing? as all the other pages are working well..

**Comment by david-oc-miller** [comment]
@Laddergrowth, was this the first time you booted the ArkCase VM?  First-time startup can be very lengthy.  If you left the VM running, ArkCase should have started.  

If you still get the proxy error, can you ssh into the VM ("vagrant ssh" if you started the VM with vagrant), and run the command "systemctl status arkcase" and post the output of that command here?

**Comment by Laddergrowth** [comment]
Thanks for the reply @david-oc-miller , I experienced that length booting when trying to vagrant up inside a VM. But after many moons decided to try in the host machine and that worked well with not a so length booting.  

"vagrant ssh" status is up and running;
![image](https://user-images.githubusercontent.com/45767956/143980095-57ba7c63-27dc-41f4-acce-e9f311af3a39.png)

i can seee the contents of 
https://arkcase-ce.local/ 
![image](https://user-images.githubusercontent.com/45767956/143980810-646b2a69-cec8-46af-ae61-cff96060346f.png)

But when going to https://arkcase-ce.local/arkcase  still showing the same message;

![image](https://user-images.githubusercontent.com/45767956/143980973-98a64f54-57c3-475b-a9bb-bc7a4baa83fd.png)

the site have all the allowed functions,
![image](https://user-images.githubusercontent.com/45767956/143982251-faa4e488-377a-4e84-a037-ad44c907246e.png)


The following are opening fine and showing the contents:

https://arkcase-ce.local/solr/#/
https://arkcase-ce.local/share/page/user/admin/dashboard

But

https://arkcase-ce.local/pentaho/Login  

is not log me in with the " Log in as an evaluator"  provided - (this might be related to the 502 proxy error?)
![image](https://user-images.githubusercontent.com/45767956/143983016-baf66730-6ce1-4dc4-a9ef-dc077b2032ff.png)

**Comment by Laddergrowth** [comment]
I am using brave but tried with Firefox and Microsoft edge.

**Comment by Laddergrowth** [comment]
I tried to access the app with Foxy Proxy, i used the ports  8843 and 8443. Port 8843 in this scenario do not go past the warning security message.

**Comment by david-oc-miller** [comment]
@Laddergrowth , for Pentaho you can login with the arkcase-admin user (not arkcase-admin@arkcase.org, but just plain arkcase-admin).

Port 8843 connects you directly to the ArkCase Tomcat service (not going through haproxy).  If you get the untrusted certificate error it means the ArkCase Tomcat did start.  In this case the non-8843 URL https://arkcase-ce.local/arkcase should also work.  If you still get the proxy error from HAProxy, it means Tomcat started, but the ArkCase web app did not start.  

If that is the case, can you send me the ArkCase catalina.out?  In the VM it should be at /opt/arkcase/log/arkcase/catalina.out, or possibly at /opt/app/arkcase/log/arkcase/catalina.out.  You can get it from the VM by something like this: `scp -P 2222 vagrant@arkcase-ce.local:/opt/app/arkcase/log/arkcase/catalina.out .`.  This is assuming you have the scp command ... on Windows you could use WinSCP to take the equivalent steps.  In case the vagrant user isn't able to read the log file, you could ssh into the VM ("vagrant ssh") and "sudo cp /opt/app/arkcase/log/arkcase/catalina.out /tmp" and "sudo chmod 644 /tmp/catalina.out" and then use scp to copy /tmp/catalina.out.

**Comment by Laddergrowth** [comment]
@david-oc-miller appreciate the instructions, managed to log in to Pentaho dashboard.

That's interesting because ArkCase show as up and running. 

I tried with the scp but was getting an error "file do not exist", I ssh into the VM and traced the file. 

I am unable to cp the content as there is no /log/ , in this case there is /logs/  but no catalina.out or the folder /arkcase/.

![image](https://user-images.githubusercontent.com/45767956/145453429-277e82b8-0bd9-4f37-b650-e90a9b12c621.png)

**Comment by Laddergrowth** [comment]
@david-oc-miller It seems the file we are after is locate at  /opt/log/arkcase   - Would this be the one? or it should be one at that location you mentioned?

![image](https://user-images.githubusercontent.com/45767956/145460611-112269fb-c25d-49fb-8475-8a1078948f40.png)

I am pasting the results here just in case it is.

**Comment by Laddergrowth** [comment]
Here is the file - the file extension is not allowed here, so there is a .txt in the end.

[catalina - Copy.out.txt](https://github.com/ArkCase/arkcase-ce/files/7688002/catalina.-.Copy.out.txt)

**Comment by JBHarris** [comment]
I'm having this same issue. Looking at maybe using ArkCase-CE for a project, but can't even test-drive it right now.
The only thing remotely "error" looking is related to checking for mail:
`2021-12-15 20:53:14,806 [ERROR] [task-scheduler-6] org.springframework.integration.handler.LoggingHandler - failure occurred while polling for mail; nested exception is javax.mail.AuthenticationFailedException: AUTHENTICATE failed.                 
2021-12-15 20:53:15,486 [ERROR] [task-scheduler-2] org.springframework.integration.handler.LoggingHandler - failure occurred while polling for mail; nested exception is javax.mail.AuthenticationFailedException: AUTHENTICATE failed. `

**Comment by david-oc-miller** [comment]
@Laddergrowth , @JBHarris , sorry for the delayed responses.  Can you ssh into the Vagrant VM (`vagrant ssh`) then run the command: `wget --no-check-certificate https://localhost:8843/arkcase`, and post the response here?  That will tell us whether the ArkCase web app started normally.  Based on your findings we will take the next step.

**Comment by david-oc-miller** [comment]
@Laddergrowth , @JBHarris ,

I pushed an update to this repository (#362).

If you remove your existing VM via `vagrant destroy`, and `git pull` to pull these changes, you should be able to deploy ArkCase 2021.02 by using the instructions in the updated README. Be sure to `export ARKCASE_WEBAPP_VERSION=2021.02` before `vagrant up`. Also follow the other updated instructions in terms of setting the hostname correctly.

Thanks,
Dave

**Comment by toninhas** [comment]
Hi @david-oc-miller I have followed the instruction and still having the same error

> Proxy Error
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request GET /arkcase/.
> 
> Reason: Error reading from remote server

But I'm able run and login Pentaho, Solr admin and Alfresco.

I checked the arkcase error file and saw this:

> , {"thread":"main","level":"ERROR","loggerName":"com.armedia.acm.scheduler.AcmScheduler","message":"Either bean with name arkcase-alfrescoSyncScheduledBean does not exist or does not implement com.armedia.acm.scheduler.AcmSchedulableBean.","thrown":{"commonElementCount":0,"localizedMessage":"No bean named 'arkcase-alfrescoSyncScheduledBean' is defined","message":"No bean named 'arkcase-alfrescoSyncScheduledBean' is defined","name":"org.springframework.beans.factory.NoSuchBeanDefinitionException"},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1642020343,"nanoOfSecond":671000000},"threadId":1,"threadPriority":5}
> , {"thread":"notificationTaskScheduler-1","level":"ERROR","loggerName":"com.armedia.acm.services.notification.service.NotificationServiceImpl","message":"Cannot send notifications to the users: null","thrown":{"commonElementCount":0,"name":"java.util.ConcurrentModificationException"},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1642020369,"nanoOfSecond":604000000},"threadId":238,"threadPriority":5}
> , {"thread":"main","level":"ERROR","loggerName":"com.armedia.acm.service.identity.service.AcmArkcaseIdentityServiceImpl","message":"Couldn't set global identity. [Not implemented yet!]","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1642020416,"nanoOfSecond":418000000},"threadId":1,"threadPriority":5}
> {"thread":"main","level":"ERROR","loggerName":"com.armedia.acm.scheduler.AcmScheduler","message":"Either bean with name arkcase-alfrescoSyncScheduledBean does not exist or does not implement com.armedia.acm.scheduler.AcmSchedulableBean.","thrown":{"commonElementCount":0,"localizedMessage":"No bean named 'arkcase-alfrescoSyncScheduledBean' is defined","message":"No bean named 'arkcase-alfrescoSyncScheduledBean' is defined","name":"org.springframework.beans.factory.NoSuchBeanDefinitionException"},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1642022311,"nanoOfSecond":676000000},"threadId":1,"threadPriority":5}
> , {"thread":"main","level":"ERROR","loggerName":"com.armedia.acm.scheduler.AcmScheduler","message":"Either bean with name arkcase-alfrescoSyncScheduledBean does not exist or does not implement com.armedia.acm.scheduler.AcmSchedulableBean.","thrown":{"commonElementCount":0,"localizedMessage":"No bean named 'arkcase-alfrescoSyncScheduledBean' is defined","message":"No bean named 'arkcase-alfrescoSyncScheduledBean' is defined","name":"org.springframework.beans.factory.NoSuchBeanDefinitionException"},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1642022334,"nanoOfSecond":306000000},"threadId":1,"threadPriority":5}
> , {"thread":"main","level":"ERROR","loggerName":"com.armedia.acm.scheduler.AcmScheduler","message":"Either bean with name arkcase-alfrescoSyncScheduledBean does not exist or does not implement com.armedia.acm.scheduler.AcmSchedulableBean.","thrown":{"commonElementCount":0,"localizedMessage":"No bean named 'arkcase-alfrescoSyncScheduledBean' is defined","message":"No bean named 'arkcase-alfrescoSyncScheduledBean' is defined","name":"org.springframework.beans.factory.NoSuchBeanDefinitionException"},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1642022334,"nanoOfSecond":471000000},"threadId":1,"threadPriority":5}
> , {"thread":"main","level":"ERROR","loggerName":"com.armedia.acm.scheduler.AcmScheduler","message":"Either bean with name arkcase-alfrescoSyncScheduledBean does not exist or does not implement com.armedia.acm.scheduler.AcmSchedulableBean.","thrown":{"commonElementCount":0,"localizedMessage":"No bean named 'arkcase-alfrescoSyncScheduledBean' is defined","message":"No bean named 'arkcase-alfrescoSyncScheduledBean' is defined","name":"org.springframework.beans.factory.NoSuchBeanDefinitionException"},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1642022335,"nanoOfSecond":503000000},"threadId":1,"threadPriority":5}
> , {"thread":"main","level":"ERROR","loggerName":"com.armedia.acm.scheduler.AcmScheduler","message":"Either bean with name arkcase-alfrescoSyncScheduledBean does not exist or does not implement com.armedia.acm.scheduler.AcmSchedulableBean.","thrown":{"commonElementCount":0,"localizedMessage":"No bean named 'arkcase-alfrescoSyncScheduledBean' is defined","message":"No bean named 'arkcase-alfrescoSyncScheduledBean' is defined","name":"org.springframework.beans.factory.NoSuchBeanDefinitionException"},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1642022335,"nanoOfSecond":590000000},"threadId":1,"threadPriority":5}
> , {"thread":"notificationTaskScheduler-1","level":"ERROR","loggerName":"com.armedia.acm.services.notification.service.NotificationServiceImpl","message":"Cannot send notifications to the users: null","thrown":{"commonElementCount":0,"name":"java.util.ConcurrentModificationException"},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1642022368,"nanoOfSecond":802000000},"threadId":227,"threadPriority":5}
> , {"thread":"main","level":"ERROR","loggerName":"com.armedia.acm.service.identity.service.AcmArkcaseIdentityServiceImpl","message":"Couldn't set global identity. [Not implemented yet!]","endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","instant":{"epochSecond":1642022397,"nanoOfSecond":640000000},"threadId":1,"threadPriority":5}

**Comment by david-oc-miller** [comment]
@toninhas , those errors wouldn't keep ArkCase from starting. Can you post the whole ArkCase catalina.out - should be at /opt/arkcase/log/arkcase/catalina.out?

**Comment by toninhas** [comment]
Hi @david-oc-miller  
Please find attached the catalina file.

[catalina.zip](https://github.com/ArkCase/arkcase-ce/files/7865481/catalina.zip)

**Comment by david-oc-miller** [comment]
@toninhas ,

In the log I see this message:

`com.armedia.acm.userinterface.angular.AngularResourceCopier - Could not copy Angular resources
  org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127)`

`Exit value: 127` may indicate a missing npm package; we did change the installer to fix this.

Can you try the following:

1. vagrant ssh <-- to enter the VM
2. sudo systemctl stop arkcase 
3. sudo su - arkcase -s /bin/bash <-- become arkcase user
4. Edit the file ~/.arkcase/acm/log4j2.xml, search for "AngularResourceCopier", and change the associated login level to debug.  In case the next step doesn't fix the problem, the debug log will tell us where to go after that.
5. rm /opt/arkcase/log/arkcase/catalina.out <-- remove current log
5. exit <-- revert to being the vagrant user instead of arkcase
6. sudo npm install -g husky  <-- install the husky package
7. sudo systemctl start arkcase

Please let me know if ArkCase starts OK after taking these steps ... if not, please send me the catalina.out file from the new ArkCase startup.

Thanks,
Dave

**Comment by toninhas** [comment]
@david-oc-miller 
Yes still not working..
[catalina.zip](https://github.com/ArkCase/arkcase-ce/files/7865856/catalina.zip)
.

**Comment by david-oc-miller** [comment]
@toninhas in the catalina.out that you just sent me, ArkCase didn't finish starting yet.  It may still not be finished.  If you still don't see the login screen now, please send me the new catalina.out.

**Comment by toninhas** [comment]
@david-oc-miller 
Please find the new file. 

[catalina.zip](https://github.com/ArkCase/arkcase-ce/files/7865947/catalina.zip)

**Comment by toninhas** [comment]
@david-oc-miller 
Please find the new file. 

[catalina.zip](https://github.com/ArkCase/arkcase-ce/files/7865947/catalina.zip)

**Comment by toninhas** [comment]
@david-oc-miller 

Seems like the error persist 
![image](https://user-images.githubusercontent.com/18728139/149409684-a28bdbee-9459-4739-9a51-3e922c3a1254.png)

**Comment by david-oc-miller** [comment]
@toninhas ,

This is the error from the catalina.out:

`
^[[m^[[36m2022-01-13 00:15:13,005 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - error /home/arkcase/.arkcase/tmp/node_modules/@bower_components/summernote: Command failed.
^[[m^[[36m2022-01-13 00:15:13,005 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Exit code: 1
^[[m^[[36m2022-01-13 00:15:13,005 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Command: husky install
^[[m^[[36m2022-01-13 00:15:13,005 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Arguments:
^[[m^[[36m2022-01-13 00:15:13,005 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Directory: /home/arkcase/.arkcase/tmp/node_modules/@bower_components/summernote
^[[m^[[36m2022-01-13 00:15:13,005 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Output:
^[[m^[[36m2022-01-13 00:15:13,005 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - .git can't be found (see https://git.io/Jc3F9)
^[[m^[[36m2022-01-13 00:15:13,005 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`

Can you run the command `husky` just to make sure it's installed OK?  

I haven't seen the `.git can't be found` before.  If you can run `husky` (which means husky did get installed), I'll have to engage some people that understand npm.

**Comment by toninhas** [comment]
@david-oc-miller  I'm able to execute the husky command

Can you check if your external plugin component is proper installed the _summernote_ (https://www.npmjs.com/package/summernote) 

You can also delete your node-modules folder and install angular dependencies again. you can use yarn install or npm install and I can try destroy de vagrant env and start again.

**Comment by david-oc-miller** [comment]
@toninhas, let's try `vagrant destroy` and then `git pull`, and send me the output of `git status`, and then `vagrant up` again.  Be sure to `export ARKCASE_WEBAPP_VERSION=2021.03` before `vagrant up` (or `set ARKCASE_WEBAPP_VERSION=2021.03` if on Windows).  We'll see what happens.

**Comment by toninhas** [comment]
@david-oc-miller 

![image](https://user-images.githubusercontent.com/18728139/149454352-86ea4a1b-27da-49a4-a66f-9ae9ab660be0.png)

![image](https://user-images.githubusercontent.com/18728139/149454406-f4e10879-a149-4880-863f-0853302c9fde.png)

**Comment by david-oc-miller** [comment]
@toninhas , thanks for this information.  I believe the Git update to the common role, should include the husky installation.  Let's see whether ArkCase starts...

**Comment by toninhas** [comment]
Hi @david-oc-miller,

Any update??

**Comment by david-oc-miller** [comment]
@toninhas , yes, I sent you an update on 14 January, which was:

"@toninhas , thanks for this information. I believe the Git update to the common role, should include the husky installation. Let's see whether ArkCase starts..."

At this moment I am waiting for you to `vagrant destroy` then `export ARKCASE_WEBAPP_VERSION=2021.03` and then `vagrant up`.  

At the end of this process, if ArkCase started OK then all is well, otherwise you'll send me another log file.

So, I am waiting to hear whether ArkCase did start, or for another log file.

**Comment by toninhas** [comment]
Hi @david-oc-miller 

[catalina.zip](https://github.com/ArkCase/arkcase-ce/files/7892016/catalina.zip)

**Comment by david-oc-miller** [comment]
@toninhas ,

This file is after ArkCase has started, and no longer has the exceptions from the startup process, which would indicate why the web context didn't start.

Please try something like this:

```bash
sudo systemctl stop arkcase
sudo rm /opt/arkcase/log/arkcase/catalina.out
sudo systemctl start arkcase
```

Then wait a few minutes, and send me that catalina.out.  

Also, please run these commands, to simulate what ArkCase does during startup:

```bash
$ vagrant ssh
Last login: Fri Jan 14 20:24:58 2022 from 10.0.2.2
[vagrant@arkcase-ce ~]$ sudo su - arkcase -s /bin/bash
[arkcase@arkcase-ce ~]$ cd .arkcase/custom
[arkcase@arkcase-ce custom]$ yarn install
yarn install v1.22.17
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 4.69s.
```

The above snippet is output from my system.  Please send me the output that you see.

Also, are you starting from a base VM created from the packer script in this repository?  If not, can you send me what operating system and release you are using? Or, are you in a geographic location that may be subject to download restrictions (Syria, Iran)?  Or, are you behind some corporate firewall that may be restricting traffic?  Can you think of anything else that could cause any issues?

Also, your catalina.out is the only one I've seen that includes binary content.  I have no idea why this happens but certainly it is very interesting.

I'm asking these questions since we installed ArkCase hundreds of times, and since fixing this latest husky issue, we can never duplicate the error your are seeing.  So I'm asking anything I can think of that may help resolve it.

Thanks,
Dave

**Comment by david-oc-miller** [comment]
@toninhas ,

Before restarting ArkCase, as the `arkcase` user please edit the file `~/.arkcase/acm/log4j2.xml`, and edit the below line:

```xml
<Logger name="com.armedia.acm.userinterface.angular.AngularResourceCopier" level="warn" additivity="false">
```

Change the level `warn` to `debug`; save the file, and then restart ArkCase.

Thanks,
Dave

**Comment by fakhreddinetrifi** [comment]
Hi @david-oc-miller,

I installed ArkCase on Center 7 using a Vagrantfile file (the configuration as you see in the screenshot below).
![image](https://user-images.githubusercontent.com/33996928/150168857-cb4b48aa-322d-4683-a810-37fd1e33e293.png)

I can access to all other services (Alfresco, Solr, Pentahol,...) without any problem, but when try to access to ArkCase webapp I faced issue "Proxy Error" (As in the screenshot below).
![issueArkCase](https://user-images.githubusercontent.com/33996928/150167264-e4b2f7d5-8ed0-455a-a47c-3bd1cdfab631.jpg)


By the way I'm following all the steps you assigned here to resolve the issue but ArkCase still not working.
You will find all the logs about ArkCase and Catalina here attached
[arkcase.zip](https://github.com/ArkCase/arkcase-ce/files/7898584/arkcase.zip)

Thanks,
Fakhry

**Comment by david-oc-miller** [comment]
@fakhreddinetrifi ,

That is clearly the `husky` issue, since I see this output in the log file:

`2022-01-19 15:51:51,107 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - /bin/sh: husky: command not found`

Although you are using the most recent Vagrant box, it is still a very old version of ArkCase, since we stopped updating the Vagranthub boxes.  Although I mean to start updating them again, it hasn't happened yet.

You can try following commands:

```bash
vagrant ssh    # to get into the VM
sudo systemctl stop arkcase
sudo npm -g install husky   # install husky
sudo systemctl start arkcase
```

These steps have resolved the issue for me before.

--
Dave

**Comment by toninhas** [comment]
Hi @david-oc-miller

I have followed all instruction but the problem with webapp arkcase still there. I'm in Mozambique we don't have any restriction. Yes I'm using the packer script in repository. My OS is window 11 pro 21H2 22000.466.

![image](https://user-images.githubusercontent.com/18728139/150214437-329a9177-989f-4c35-a1a0-e0e46d55044c.png)

[catalina.zip](https://github.com/ArkCase/arkcase-ce/files/7900586/catalina.zip)

**Comment by david-oc-miller** [comment]
@fakhreddinetrifi , did installing husky globally resolve the issue for you?

**Comment by david-oc-miller** [comment]
@toninhas , the last catalina.zip you sent, the Angular resource copier was still running, so it didn't yet either start up successfully or have any errors.

The last line is this one:

`2022-01-18 21:36:07,594 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - warning karma > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.`

Which tells me the startup is still in process.  

I apologize for the amount of time this is taking.  If the `yarn install` really didn't work for you, I may end up pushing a special build to Vagranthub with the newest ArkCase version having already started, and you can try out that one.

--
Dave

**Comment by toninhas** [comment]
Hi @david-oc-miller 

Sorry about my late reply. please find attached the Catalina log.

[catalina.zip](https://github.com/ArkCase/arkcase-ce/files/7992810/catalina.zip)

**Comment by david-oc-miller** [comment]
@toninhas ,

I see the same old Husky error again:

`^[[m^[[36m2022-02-03 07:54:30,223 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - error /home/arkcase/.arkcase/tmp/node_modules/@bower_components/summernote: Command failed.
^[[m^[[36m2022-02-03 07:54:30,223 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Exit code: 1
^[[m^[[36m2022-02-03 07:54:30,223 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Command: husky install
^[[m^[[36m2022-02-03 07:54:30,223 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Arguments:
^[[m^[[36m2022-02-03 07:54:30,224 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Directory: /home/arkcase/.arkcase/tmp/node_modules/@bower_components/summernote
^[[m^[[36m2022-02-03 07:54:30,224 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Output:
^[[m^[[36m2022-02-03 07:54:30,224 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - .git can't be found (see https://git.io/Jc3F9)
`

Let's try to disable Husky completely.

In the file `/opt/arkcase/app/arkcase/bin/setenv.sh`, you should see a number of environment variables, e.g. `NODE_ENV` and `CATALINA_OPTS`.  At the very bottom of this file, add a line like so:

`export HUSKY=0`

Then restart ArkCase: `sudo systemctl restart arkcase`

And we will see what happens.

Thanks,
Dave

**Comment by toninhas** [comment]
Hi @david-oc-miller 

Still not working.
[catalina.zip](https://github.com/ArkCase/arkcase-ce/files/8053171/catalina.zip)

**Comment by kamezamw** [comment]
hi

I am also facing the proxy error, tried the suggested solutions but not working. Destroyed the VM several times but still facing the same proxy error. 

however, on under my catalina.out file only show one error message
"2022-05-16 04:00:00,349 [ERROR] [deleteExpiredUrlsScheduler-1] org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task."

**Comment by setsanderson** [comment]
Hi everyone!
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/111231529/184537912-ebe8b87d-f758-4d0c-bd18-d04b0b174899.png">

I am facing the same issue, and i tried suggested instructions above but no luck. Did anyone managed to pass this issue.  

This issue is reported on another issue, i will follow instructions there. Thank you.

**Comment by srinivasagunturu** [comment]
Hi kamezamw,

Could you please  edit the file /home/arkcase/.arkcase/acm/log4j2.xml; find the line for AngularResourceCopier; and change the log level to DEBUG.

you can see like this
Logger name="com.armedia.acm.userinterface.angular.AngularResourceCopier" level="debug" additivity="false"

Once changes done kindly take the arkcase restart using below command and share the catalina.out file to check further.

sudo systemctl restart arkcase

Log file path: /opt/akcase/log/arkcase/catalina.out

Thanks
Srinivas|ARMEDIA

**Comment by danb35** [comment]
I'm having what seems to be the same problem; here's what appears to be the relevant portion of `catalina.out`:
```
m[36m2022-11-08 23:31:24,891 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - [4/4] Building fresh packages...
[m[36m2022-11-08 23:31:26,457 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - error /home/arkcase/.arkcase/tmp/node_modules/@bower_components/summernote: Command failed.
[m[36m2022-11-08 23:31:26,457 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Exit code: 1
[m[36m2022-11-08 23:31:26,457 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Command: husky install
[m[36m2022-11-08 23:31:26,457 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Arguments: 
[m[36m2022-11-08 23:31:26,457 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Directory: /home/arkcase/.arkcase/tmp/node_modules/@bower_components/summernote
[m[36m2022-11-08 23:31:26,457 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - Output:
[m[36m2022-11-08 23:31:26,457 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
[m[36m2022-11-08 23:31:26,457 [DEBUG] [Exec Stream Pumper] com.armedia.acm.userinterface.angular.AngularResourceCopier - info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[m[1;31m2022-11-08 23:31:27,662 [ERROR] [main] com.armedia.acm.userinterface.angular.AngularResourceCopier - Could not copy Angular resources
[m org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```
I've already tried to install husky (with `sudo npm -g install husky`); this error appears after doing this.  The complete catalina.out is attached.
[catalina.out.bak.zip](https://github.com/ArkCase/arkcase-ce/files/9966037/catalina.out.bak.zip)

**Comment by david-oc-miller** [comment]
@danb35 , thanks for posting the log fragment.

I read this page, https://typicode.github.io/husky/#/?id=custom-directory, referenced in your log output.  In the VM's setenv.sh file, try adding a line `export HUSKY=0`.  This file should be at /opt/app/arkcase/app/arkcase/bin/setenv.sh, or possibly at /opt/arkcase/app/arkcase/bin/setenv.sh.

**Comment by danb35** [comment]
Thanks for the quick response; turns out it's at `/opt/app/arkcase/bin/setenv.sh`.  I stopped arkcase (`systemctl stop arkcase`), made that change, and restarted arkcase.  After waiting a bit, the login page came up, and I was able to log in as the default admin user.  That leaves two questions:

* Is this just a temporary troubleshooting step, or does this actually fix the problem?  Put differently, does turning off Husky result in any problems or limitations?
* It looks like the next step is to set up outgoing email (https://github.com/ArkCase/arkcase-ce#set-up-outgoing-email).  But when I do that, I get a message that "SMTP settings are not valid," with no further explanation.  I guess that'd be a matter for a different issue, though.

**Comment by david-oc-miller** [comment]
@danb35 , husky apparently is a git accessory: "Modern native git hooks made easy".  Our Git repository uses "conventional commits" and husky seems to be a tool to enforce proper commit messages.  That is why the Husky page has so many different ways to disable husky in situations like this where we aren't writing new code, only trying to run ArkCase.

To summarize: you won't see any problems or limitations.

What SMTP server are you using?  We had some issues with some servers in the past.

**Comment by danb35** [comment]
> What SMTP server are you using? We had some issues with some servers in the past.

I'm using an installation of Nethserver 7 as my mail server, which I believe uses Postfix.  But despite how I set it (port 25/no encryption, port 465/SSL/TLS, port 587/STARTTLS, port 25/STARTTLS), I'm getting this error in `catalina.out`:
```
2022-11-09 11:26:22,939 [ERROR] [https-openssl-apr-0.0.0.0-8843-exec-4] com.armedia.acm.services.email.sender.service.EmailSenderConfigurationServiceImpl - SMTP Error, [Unrecognized SSL message, plaintext connection?]
	at org.apache.commons.net.smtp.SMTPSClient.performSSLNegotiation(SMTPSClient.java:200) ~[commons-net-3.3.jar:3.3]
	at org.apache.commons.net.smtp.SMTPSClient._connectAction_(SMTPSClient.java:159) ~[commons-net-3.3.jar:3.3]
```
Including a little more context (`grep -C 20 SMTP catalina.out`) gives this:
```
2022-11-09 11:26:22,939 [ERROR] [https-openssl-apr-0.0.0.0-8843-exec-4] com.armedia.acm.services.email.sender.service.EmailSenderConfigurationServiceImpl - SMTP Error, [Unrecognized SSL message, plaintext connection?]
 javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710) ~[?:1.8.0_222]
	at sun.security.ssl.InputRecord.read(InputRecord.java:527) ~[?:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975) ~[?:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[?:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[?:1.8.0_222]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[?:1.8.0_222]
	at org.apache.commons.net.smtp.SMTPSClient.performSSLNegotiation(SMTPSClient.java:200) ~[commons-net-3.3.jar:3.3]
	at org.apache.commons.net.smtp.SMTPSClient._connectAction_(SMTPSClient.java:159) ~[commons-net-3.3.jar:3.3]
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:183) ~[commons-net-3.3.jar:3.3]
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:203) ~[commons-net-3.3.jar:3.3]
	at com.armedia.acm.services.email.sender.service.EmailSenderConfigurationServiceImpl.validateSmtpConfiguration(EmailSenderConfigurationServiceImpl.java:82) [acm-service-email-3.3.1-r1.jar:?]
	at com.armedia.acm.plugins.admin.web.api.EmailSenderConfigurationAPIController.validateSmtpConfiguration(EmailSenderConfigurationAPIController.java:98) [acm-admin-plugin-3.3.1-r1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) [spring-web-4.2.9.RELEASE.jar:4.2.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) [spring-web-4.2.9.RELEASE.jar:4.2.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) [spring-webmvc-4.2.9.RELEASE.jar:4.2.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:832) [spring-webmvc-4.2.9.RELEASE.jar:4.2.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:743) [spring-webmvc-4.2.9.RELEASE.jar:4.2.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.2.9.RELEASE.jar:4.2.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961) [spring-webmvc-4.2.9.RELEASE.jar:4.2.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895) [spring-webmvc-4.2.9.RELEASE.jar:4.2.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967) [spring-webmvc-4.2.9.RELEASE.jar:4.2.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:880) [spring-webmvc-4.2.9.RELEASE.jar:4.2.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:663) [servlet-api.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) [spring-webmvc-4.2.9.RELEASE.jar:4.2.9.RELEASE]
```

**Comment by Mhorneh2** [comment]
Hi

I am trying to install the arkcase-ce with Vagrant/Virtualbox. 
When the build is run I encounter the proxy error mentioned earlier in this thread however when I try to obtain additional logs from the command "sudo cp /opt/app/arkcase/log/arkcase/catalina.out it encounters a prompt for the sudo password for arkcase: 
In this field I've tried the @rKc@3e and vagrant which I have found as the passwords in the readme's and configuration files. 
Is there another documented location for this password so that I can obtain these logs? 

The VM Build file in use is; 
Vagrant.configure("2") do |config|
  config.vm.box = "arkcase/arkcase-ce"
  config.vm.box_version = "3.3.1-r1-a"
  config.vm.box_url = "https://app.vagrantup.com/arkcase/boxes/arkcase-ce"
  config.vm.network "public_network", bridge: "Intel(R) Wireless-AC 9560 160Mhz"
  config.vm.hostname = "arkcase-ce.local"
  # disable the default synced folder
  config.vm.synced_folder '.', '/vagrant', disabled: true
end

Within this build I can access the Pentaho, Solr and Alfresco pages but not the ArkCase CE 

Any further steps I could test or check that I have missed would be appreciated. 

Thanks,
Michael

**Comment by srinivasagunturu** [comment]
Hi @Laddergrowth ,

Thank you for contacting ArkCase Support, we will take a look into your issue and get back to you shortly.

Thanks & Regards
Srinivasa Reddy G
Armedia |ArkCase Application Support
[srinivasa.gunturu@armedia.com]

**Comment by srinivasagunturu** [comment]
Hi @Laddergrowth ,

Sorry for the delayed response; please see the attached document and follow the steps to install Arkcase on your local system.[](url)
[Steps for Arkcase-Ce local.docx](https://github.com/ArkCase/arkcase-ce/files/12239958/Steps.for.Arkcase-Ce.local.docx)

**Comment by chr0sy** [comment]
hi, i am having same issue and nothing of the above solutions seems to work. anyone can help me? i want to test arkcase if it's really suitable for my use case

**Comment by chr0sy** [comment]
attached my catalina.out 
[catalina.zip](https://github.com/ArkCase/arkcase-ce/files/13633761/catalina.zip)

**Comment by chr0sy** [comment]
i also get permission denied everywhere near /opt/arkcase/app/arkcase/bin/ to try to disable husky as the above mentioned, using the vagrant user.

 i also cannot find sudo arkcase password ?

**Comment by saisworld** [comment]
@srinivasagunturu @david-oc-miller 

Hi,

I'm also facing the same issue with Proxy error while trying to run https://arkcase-ce.local/arkcase. Any help will be appreciated.

I have followed the instructions from here -  https://github.com/ArkCase/arkcase-ce?tab=readme-ov-file#how-to-run-arkcase

I can run Pentaho, Solr, Alfresco without any error. But I can't seem to run arkcase. Keeps failing with Proxy error.

I tried the above mentioned fixes - 

```
vagrant ssh <-- to enter the VM
sudo systemctl stop arkcase
sudo su - arkcase -s /bin/bash <-- become arkcase user
Edit the file ~/.arkcase/acm/log4j2.xml, search for "AngularResourceCopier", and change the associated login level to debug. In case the next step doesn't fix the problem, the debug log will tell us where to go after that.
rm /opt/arkcase/log/arkcase/catalina.out <-- remove current log
exit <-- revert to being the vagrant user instead of arkcase
sudo npm install -g husky <-- install the husky package
sudo systemctl start arkcase
```

Also this  - 

`Logger name="com.armedia.acm.userinterface.angular.AngularResourceCopier" level="debug" additivity="false"`

and also this - 
set the  `export HUSKY=0`  in the file ` /opt/app/arkcase/bin/setenv.sh.`  and restarted arkcase.


attached below is the catalina.out file.

Please advise

[catalina.zip](https://github.com/ArkCase/arkcase-ce/files/14191632/catalina.zip)
